language: java

branches:
  only:
    - master

jdk:
  - openjdk8
  - oraclejdk8

notifications:
  email: true

addons:
  sonarcloud:
    organization: "malkomich-github"
    token:
      secure: ${SONAR_TOKEN}

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
